# Generated by Django 4.0.1 on 2022-01-12 14:58

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated',
            field=models.DateTimeField(auto_now=True, unique=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='اسم المنتج')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المنتج')),
                ('type_Product', models.CharField(default='الكمية', help_text='هل المنتج با الكيلو ام با القطعه ام ب العلبة', max_length=11, verbose_name='نوع المنتج ')),
                ('price', models.FloatField(verbose_name='السعر')),
                ('discount', models.FloatField(blank=True, null=True, verbose_name='تخفيض')),
                ('start', models.FloatField(default=1, verbose_name='الحجم')),
                ('stock', models.BooleanField(default=True, verbose_name='هل المنتج متواجد ')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category', verbose_name='الصنف')),
            ],
            bases=(models.Model, django.db.models.manager.Manager),
        ),
    ]
