# Generated by Django 4.0.1 on 2022-01-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_slug_alter_category_updated_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_Product',
            field=models.CharField(default='الكمية', help_text='هل المنتج با الكيلو ام با القطعه ام ب العلبة', max_length=20, verbose_name='نوع المنتج '),
        ),
    ]
