# Generated by Django 4.0.1 on 2022-01-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('تم الطلب', 1), ('تم التوصيل', 2)], default=1, max_length=50),
        ),
    ]
