# Generated by Django 4.0.1 on 2022-02-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_order',
            field=models.IntegerField(default=0),
        ),
    ]
