# Generated by Django 4.0.1 on 2022-02-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_count_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('تم الطلب', 'تم الطلب'), ('تم التوصيل', 'تم التوصيل')], default=1, max_length=50),
        ),
    ]
