# Generated by Django 4.0.1 on 2022-02-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('تم الطلب', 'تم الطلب'), ('تم التوصيل', 'تم التوصيل')], default='تم الطلب', max_length=50),
        ),
    ]
