# Generated by Django 4.0.1 on 2022-04-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
