# Generated by Django 4.0.1 on 2022-01-17 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='region',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='customer.region'),
            preserve_default=False,
        ),
    ]
