# Generated by Django 4.0.1 on 2022-01-17 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customer_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='region',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.region'),
        ),
    ]
