# Generated by Django 4.0.1 on 2022-01-17 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customer_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.region'),
        ),
    ]
