# Generated by Django 4.0.1 on 2022-02-10 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
