# Generated by Django 4.0.1 on 2022-02-13 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopProduct',
        ),
    ]
